[package]
name = "rust"
version = "0.1.0"
authors = ["johnathan <johnathanfercher22@gmail.com>"]

[dependencies]
protobuf = "1.0.24"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"

